# Generated by Django 5.2 on 2025-04-04 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_remove_cartitem_product_productvariant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='name',
            new_name='spice_level',
        ),
    ]
