# Generated by Django 5.2 on 2025-04-04 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_rename_name_productvariant_spice_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='price_override',
        ),
    ]
