# Generated by Django 5.2 on 2025-04-04 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_remove_productvariant_price_override'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='variant',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application.product'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
    ]
