# Generated by Django 5.2 on 2025-04-08 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variant',
            field=models.CharField(choices=[('MILD', 'Mild 🔥'), ('HOT', 'Hot 🔥🔥'), ('CYM', 'Call Your Momma 🔥🔥🔥')], default='MILD', max_length=10),
        ),
    ]
