# Generated by Django 5.2 on 2025-04-08 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_product_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='variant',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variant',
            field=models.CharField(choices=[('MILD', 'Mild 🔥'), ('HOT', 'Hot 🔥🔥'), ('CYM', 'Call Your Momma 🔥🔥🔥')], default='MILD', max_length=10),
        ),
    ]
