# Generated by Django 5.2 on 2025-04-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_remove_product_variant_cartitem_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='variant',
            field=models.CharField(choices=[('MILD', 'MILD🔥'), ('HOT', 'HOT🔥🔥'), ('CYM', 'CYM🔥🔥🔥')], default='MILD', max_length=10),
        ),
    ]
